name: Update location.txt

on:
  push:
    branches:
      - main

jobs:
  update-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Commit location.txt
        run: |
          git config --global user.name "anas frikel"
          git config --global user.email "afrikel173@gmail.com"
          git add location.txt
          git commit -m "Update location data"
          git push
